# Opioid Crisis - Analysis

I want to take a second look at the data from the Opioid Crisis datasheet.

- (link here: https://www.mathmodels.org/Problems/2019/MCM-C/index.html)

Motivation: worked on it during 2019 for two days (MCM). Still interested.

Data we will work with:
* Drug identification counts in years 2010-2016
* Socio-economic factors collected for five states (Ohio, Kentucky, West Virginia, Virginia, Pennsylvania)

In [1]:
import numpy as np
import pandas as pd

# drug use data.
df_nflis = pd.read_excel('2018_MCMProblemC_DATA/MCM_NFLIS_Data.xlsx', sheet_name="Data")

# socio-economic data.
df10 = pd.read_csv('2018_MCMProblemC_DATA/ACS_10_5YR_DP02/ACS_10_5YR_DP02_with_ann.csv')
df11 = pd.read_csv('2018_MCMProblemC_DATA/ACS_11_5YR_DP02/ACS_11_5YR_DP02_with_ann.csv')
df12 = pd.read_csv('2018_MCMProblemC_DATA/ACS_12_5YR_DP02/ACS_12_5YR_DP02_with_ann.csv')
df13 = pd.read_csv('2018_MCMProblemC_DATA/ACS_13_5YR_DP02/ACS_13_5YR_DP02_with_ann.csv')
df14 = pd.read_csv('2018_MCMProblemC_DATA/ACS_14_5YR_DP02/ACS_14_5YR_DP02_with_ann.csv')
df15 = pd.read_csv('2018_MCMProblemC_DATA/ACS_15_5YR_DP02/ACS_15_5YR_DP02_with_ann.csv')
df16 = pd.read_csv('2018_MCMProblemC_DATA/ACS_16_5YR_DP02/ACS_16_5YR_DP02_with_ann.csv')

# indexing data.
df10_meta = pd.read_csv('2018_MCMProblemC_DATA/ACS_10_5YR_DP02/ACS_10_5YR_DP02_metadata.csv')
df11_meta = pd.read_csv('2018_MCMProblemC_DATA/ACS_11_5YR_DP02/ACS_11_5YR_DP02_metadata.csv')
df12_meta = pd.read_csv('2018_MCMProblemC_DATA/ACS_12_5YR_DP02/ACS_12_5YR_DP02_metadata.csv')
df13_meta = pd.read_csv('2018_MCMProblemC_DATA/ACS_13_5YR_DP02/ACS_13_5YR_DP02_metadata.csv')
df14_meta = pd.read_csv('2018_MCMProblemC_DATA/ACS_14_5YR_DP02/ACS_14_5YR_DP02_metadata.csv')
df15_meta = pd.read_csv('2018_MCMProblemC_DATA/ACS_15_5YR_DP02/ACS_15_5YR_DP02_metadata.csv')
df16_meta = pd.read_csv('2018_MCMProblemC_DATA/ACS_16_5YR_DP02/ACS_16_5YR_DP02_metadata.csv')

Parts of the data are not available.

## Preprocessing

General plan: iterate over socio-economic data, and append with relevant drug use data.

Feature extraction part:
* Include geography (specifically `GEO.display-label`).
* Exclude margin of error features.
* Exclude columns with `(X)`.
* Exclude non-universal data.

In [2]:
df10

GEO.id GEO.id2              GEO.display-label  \
0                Id     Id2                      Geography   
1    0500000US21001   21001         Adair County, Kentucky   
2    0500000US21003   21003         Allen County, Kentucky   
3    0500000US21005   21005      Anderson County, Kentucky   
4    0500000US21007   21007       Ballard County, Kentucky   
..              ...     ...                            ...   
460  0500000US54101   54101  Webster County, West Virginia   
461  0500000US54103   54103   Wetzel County, West Virginia   
462  0500000US54105   54105     Wirt County, West Virginia   
463  0500000US54107   54107     Wood County, West Virginia   
464  0500000US54109   54109  Wyoming County, West Virginia   

                                           HC01_VC03  \
0    Estimate; HOUSEHOLDS BY TYPE - Total households   
1                                               7272   
2                                               7811   
3                                               8319   
4                                               3363   
..                                               ...   
460                                             4116   
461                                             6897   
462                                             2364   
463                                            36222   
464                                             9126   

                                             HC02_VC03  \
0    Estimate Margin of Error; HOUSEHOLDS BY TYPE -...   
1                                                  270   
2                                                  291   
3                                                  205   
4                                                  146   
..                                                 ...   
460                                                214   
461                                                223   
462                                                170   
463                                                475   
464                                                289   

                                          HC03_VC03  \
0    Percent; HOUSEHOLDS BY TYPE - Total households   
1                                              7272   
2                                              7811   
3                                              8319   
4                                              3363   
..                                              ...   
460                                            4116   
461                                            6897   
462                                            2364   
463                                           36222   
464                                            9126   

                                             HC04_VC03  \
0    Percent Margin of Error; HOUSEHOLDS BY TYPE - ...   
1                                                  (X)   
2                                                  (X)   
3                                                  (X)   
4                                                  (X)   
..                                                 ...   
460                                                (X)   
461                                                (X)   
462                                                (X)   
463                                                (X)   
464                                                (X)   

                                             HC01_VC04  \
0    Estimate; HOUSEHOLDS BY TYPE - Family househol...   
1                                                 5004   
2                                                 5526   
3                                                 6148   
4                                                 2408   
..                                                 ...   
460                                               2927   
461                                               4725   
462               

The function `feature_extract` will extract features as to satisfy the above conditions (save universality).

In [3]:
from opioid_crisis_lib import feature_extract
df10[feature_extract(df10, df10_meta)]

GEO.display-label  \
0                        Geography   
1           Adair County, Kentucky   
2           Allen County, Kentucky   
3        Anderson County, Kentucky   
4         Ballard County, Kentucky   
..                             ...   
460  Webster County, West Virginia   
461   Wetzel County, West Virginia   
462     Wirt County, West Virginia   
463     Wood County, West Virginia   
464  Wyoming County, West Virginia   

                                           HC01_VC03  \
0    Estimate; HOUSEHOLDS BY TYPE - Total households   
1                                               7272   
2                                               7811   
3                                               8319   
4                                               3363   
..                                               ...   
460                                             4116   
461                                             6897   
462                                             2364   
463                                            36222   
464                                             9126   

                                             HC01_VC04  \
0    Estimate; HOUSEHOLDS BY TYPE - Family househol...   
1                                                 5004   
2                                                 5526   
3                                                 6148   
4                                                 2408   
..                                                 ...   
460                                               2927   
461                                               4725   
462                                               1697   
463                                              23934   
464                                               6565   

                                             HC01_VC06  \
0    Estimate; HOUSEHOLDS BY TYPE - Family househol...   
1                                                 1945   
2                                                 2363   
3                                                 2771   
4                                                 1001   
..                                                 ...   
460                                               1189   
461                                               1728   
462                                                601   
463                                               9622   
464                                               2475   

                                             HC01_VC07  \
0    Estimate; HOUSEHOLDS BY TYPE - Family househol...   
1                                                 4124   
2                                                 4011   
3                                                 4848   
4                                                 2001   
..                                                 ...   
460                                               2365   
461                                               3845   
462                                               1447   
463                                              18641   
464                                               5288   

                                             HC01_VC08  \
0    Estimate; HOUSEHOLDS BY TYPE - Family househol...   
1                                                 1506   
2                                                 1519   
3                                                 1891   
4                                                  725   
..                                                 ...   
460                                                884   
461                                               1275   
462                                                441   
463                                               6666   
464                                               1843   

                                             HC01_VC09  \
0    Estimate; HOUSEHOLDS BY TYPE - Famil

### Filtering Data with Universal Property

We can only work with properties that are present for all dataframes.

At the same time, the heterogenous nature of labels corresponding to the same descriptor across years prompts us to address that as well, with the following map:
$$\mathrm{descriptor}\mapsto(\mathrm{year}\mapsto\mathrm{label})$$

In [4]:
from opioid_crisis_lib import feature_index
from opioid_crisis_lib import feature_index2

# ddf = [df10, df11, df12, df13, df14, df15, df16]
# ddf_metadata = [df10_meta, df11_meta, df12_meta, df13_meta, df14_meta, df15_meta, df16_meta]

ddf_yyyy = {
    "2010": df10,
    "2011": df11,
    "2012": df12,
    "2013": df13,
    "2014": df14,
    "2015": df15,
    "2016": df16,
}
ddf_metadata_yyyy = {
    "2010": df10_meta,
    "2011": df11_meta,
    "2012": df12_meta,
    "2013": df13_meta,
    "2014": df14_meta,
    "2015": df15_meta,
    "2016": df16_meta,
}

# f_index = feature_index(ddf, ddf_metadata)
# sorted(f_index)

f_index = feature_index2(ddf_yyyy, ddf_metadata_yyyy)
sorted(f_index)

['Estimate; ANCESTRY - Total population',
 'Estimate; EDUCATIONAL ATTAINMENT - Population 25 years and over',
 'Estimate; FERTILITY - Number of women 15 to 50 years old who had a birth in the past 12 months',
 'Estimate; GRANDPARENTS - Number of grandparents living with own grandchildren under 18 years',
 'Estimate; GRANDPARENTS - Number of grandparents responsible for own grandchildren under 18 years',
 'Estimate; HOUSEHOLDS BY TYPE - Households with one or more people 65 years and over',
 'Estimate; HOUSEHOLDS BY TYPE - Households with one or more people under 18 years',
 'Estimate; HOUSEHOLDS BY TYPE - Total households',
 'Estimate; LANGUAGE SPOKEN AT HOME - Population 5 years and over',
 'Estimate; MARITAL STATUS - Females 15 years and over',
 'Estimate; MARITAL STATUS - Males 15 years and over',
 'Estimate; PLACE OF BIRTH - Total population',
 'Estimate; RELATIONSHIP - Population in households',
 'Estimate; RESIDENCE 1 YEAR AGO - Population 1 year and over',
 'Estimate; SCHOOL ENR

As we see only the "important" data remain. We've gotten rid of error estimate data as well as inadmissible data.

Given a particular year we want to extract all universal relevant labels. In other words, we want the map:
$$
\left(\mathrm{descriptor}\mapsto(\mathrm{year}\mapsto\mathrm{label})\right)
\mapsto\left(\mathrm{year}\mapsto(\mathrm{labels})\right)
$$

In [5]:
from opioid_crisis_lib import label_from_feature_index
label_from_feature_index("2012", f_index)

['HC01_VC35',
 'HC01_VC69',
 'HC01_VC42',
 'HC01_VC117',
 'HC01_VC182',
 'HC01_VC144',
 'HC01_VC150',
 'HC01_VC61',
 'HC01_VC84',
 'HC01_VC138',
 'HC01_VC18',
 'HC01_VC51',
 'HC01_VC146',
 'HC01_VC98',
 'HC01_VC156',
 'HC01_VC03',
 'HC01_VC166',
 'HC01_VC75',
 'HC01_VC128',
 'HC01_VC25',
 'HC01_VC17']

In [6]:
f_index['Estimate; ANCESTRY - Total population']

{'2010': 'HC01_VC182',
 '2011': 'HC01_VC182',
 '2012': 'HC01_VC182',
 '2013': 'HC01_VC185',
 '2014': 'HC01_VC185',
 '2015': 'HC01_VC185',
 '2016': 'HC01_VC185'}

We obtain a map from descriptors to corresponding labels. This allows us to go back and forth between description and label.

The above data corresponds to the socio-economic data of a particular county at some specified year. When we go over drug use data, the `YYYY`, `State` and `County` data should sufficiently return the appropriate socio-economic data.

The following short function returns the state and county of a string as separate strings, with state written in initials.

In [7]:
from opioid_crisis_lib import state_and_county
state_and_county("Adair County, Kentucky")

('ky', 'Adair', 'Kentucky')

### Retrieving Geographic Data

In addition, for each county there should be a method to retrieve numerical geographic data:

In [8]:
df_geo = pd.read_csv('2021_Gaz_counties_national.txt', sep="\t")
from opioid_crisis_lib import locate
locate("ky", "adair", df_geo)

(37.105559, -85.28138)

In [9]:
np.array(df_geo[["USPS", "NAME"]])

array([['AL', 'Autauga County'],
       ['AL', 'Baldwin County'],
       ['AL', 'Barbour County'],
       ...,
       ['PR', 'Villalba Municipio'],
       ['PR', 'Yabucoa Municipio'],
       ['PR', 'Yauco Municipio']], dtype=object)

### Processing Drug Data

In [10]:
df_nflis[["YYYY", "State", "COUNTY", "SubstanceName", "DrugReports"]]

YYYY State           COUNTY  SubstanceName  DrugReports
0      2010    VA         ACCOMACK   Propoxyphene            1
1      2010    OH            ADAMS       Morphine            9
2      2010    PA            ADAMS      Methadone            2
3      2010    VA  ALEXANDRIA CITY         Heroin            5
4      2010    PA        ALLEGHENY  Hydromorphone            5
...     ...   ...              ...            ...          ...
24057  2017    VA            WYTHE        Codeine            1
24058  2017    VA            WYTHE    Hydrocodone           19
24059  2017    VA            WYTHE       Tramadol            5
24060  2017    PA             YORK           ANPP            1
24061  2017    VA             YORK         Heroin           48

[24062 rows x 5 columns]

Of importance is the type of drugs reported.

In [11]:
df_nflis["SubstanceName"]

0         Propoxyphene
1             Morphine
2            Methadone
3               Heroin
4        Hydromorphone
             ...      
24057          Codeine
24058      Hydrocodone
24059         Tramadol
24060             ANPP
24061           Heroin
Name: SubstanceName, Length: 24062, dtype: object

The following gives a survey of distinct drug types (indexed).

In [12]:
substanceNames = sorted(set(df_nflis["SubstanceName"]))
substanceNames

['3,4-Methylenedioxy U-47700',
 '3-Fluorofentanyl',
 '3-Methylfentanyl',
 '4-Fluoroisobutyryl fentanyl',
 '4-Methylfentanyl',
 'ANPP',
 'Acetyl fentanyl',
 'Acetylcodeine',
 'Acetyldihydrocodeine',
 'Acryl fentanyl',
 'Alphaprodine',
 'Benzylfentanyl',
 'Buprenorphine',
 'Butorphanol',
 'Butyryl fentanyl',
 'Carfentanil',
 'Codeine',
 'Crotonyl fentanyl',
 'Cyclopentyl fentanyl',
 'Cyclopropyl fentanyl',
 'Cyclopropyl/Crotonyl Fentanyl',
 'Desmethylprodine ',
 'Dextropropoxyphene',
 'Dihydrocodeine',
 'Dihydromorphone',
 'Fentanyl',
 'Fluorobutyryl fentanyl ',
 'Fluorofentanyl',
 'Fluoroisobutyryl fentanyl',
 'Furanyl fentanyl',
 'Furanyl/3-Furanyl fentanyl',
 'Heroin',
 'Hydrocodeinone',
 'Hydrocodone',
 'Hydromorphone',
 'Isobutyryl fentanyl',
 'Levorphanol',
 'MT-45',
 'Meperidine',
 'Metazocine',
 'Methadone',
 'Methorphan',
 'Methoxyacetyl fentanyl',
 'Mitragynine',
 'Morphine',
 'Nalbuphine',
 'Opiates',
 'Opium',
 'Oxycodone',
 'Oxymorphone',
 'Pentazocine',
 'Pethidine',
 'Phen

In [13]:
print(len(substanceNames))

69


Convert this to a dictionary so we can map substance use to a particular index.

In [14]:
substanceNamesDict = {substanceNames[i]:i for i in range(69)}

Given data on `drug reports` and `substance name`, we can construct a vector which indicates extent of a particular drug use in a county.

In [15]:
from opioid_crisis_lib import drug_matrix
drug_matrix(df_nflis, substanceNamesDict)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

Now due to redundancy, a single county may occur multiple times. We want to have one drug vector per county.

In [16]:
from opioid_crisis_lib import drug_vector
drug_vector("2010", "oh", "adams", df_nflis, substanceNamesDict, identify=True)

(array([  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   6.,   0.,   0.,   0.,   3.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  50.,   0.,
         59.,   4.,   0.,   0.,   0.,   1.,   0.,  12.,   0.,   0.,   0.,
          9.,   0.,   0.,   0., 119.,   1.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.]),
 {'Morphine': 9,
  'Buprenorphine': 6,
  'Heroin': 50,
  'Tramadol': 1,
  'Codeine': 3,
  'Hydrocodone': 59,
  'Methadone': 12,
  'Hydromorphone': 4,
  'Meperidine': 1,
  'Oxycodone': 119,
  'Oxymorphone': 1})

### Compiling Data

We can do this:
1. Determine the overall dimension of the sample matrix. (doable)
1. Iterate through socio-economic dataframe rows, through the years 2010-2016,
    1. For each row, gather socio-economic data, AND data which identifies the State, county and year.
    1. Retrieve the geographic location of the county, append.
    1. Retrieve the drug vector of the county, append.
2. Write all appended data into one numpy array.
3. (Optional) Move independent columns (geographical location, socio-economic data) to the beginning, and the drug vector to the end.

**Note**: even with previous filtering, there are still socio-economic sample points with `(X)` terms. These terms are set to 0. (Not the best approach. we'll deal with this later. But I assume that these anomalous rows only take a small portion and are negligible.)

**Note**: turns out that the drug data contains data up to 2017, which is not included in the socio-economic data. However, this new data also contains new drugs, which messes up the data (since the new-drug column is a column of zeros, which messes up pca and all that).

Make sure the data is recoverable and that rows have unique identifiers. (which indicate year, state and county)

In [17]:
# from opioid_crisis_lib import generate_sample
# sample = generate_sample(ddf_yyyy, ddf_metadata_yyyy, f_index, df_nflis, substanceNamesDict, df_geo)
# sample

In [18]:
# np.savetxt("please_dont_overwrite.csv", sample, delimiter=",")

In [19]:
sample_read = pd.read_csv('please_dont_overwrite.csv', header=None)
sample_read

0          1        2      3        4        5        6       7   \
0     37.105559 -85.281380   4541.0  236.0   2113.0  18542.0  18378.0   271.0   
1     36.750770 -86.192458   4549.0  314.0   1995.0  19688.0  19416.0   477.0   
2     38.005396 -84.986417   5407.0  369.0   1719.0  21080.0  20857.0   517.0   
3     37.051323 -89.010367   1911.0   51.0    987.0   8225.0   8080.0    51.0   
4     36.962805 -85.932108   9693.0  605.0   4591.0  41685.0  41150.0  1109.0   
...         ...        ...      ...    ...      ...      ...      ...     ...   
3240  38.483459 -80.449052   1492.0  206.0   1351.0   8820.0   8743.0   479.0   
3241  39.598180 -80.635399   3021.0  182.0   2333.0  15997.0  15766.0   378.0   
3242  39.020034 -81.382975   1102.0   16.0    777.0   5826.0   5747.0    37.0   
3243  39.211602 -81.516234  18959.0  862.0  11546.0  86262.0  85254.0  1718.0   
3244  37.603660 -81.549032   4428.0  466.0   3104.0  22537.0  22326.0   595.0   

           8        9   ...   82   83   84   85   86   87   88   89   90   91  
0      7272.0   2258.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1      7811.0   2662.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2      8319.0   3137.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3      3363.0   1064.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4     16727.0   5565.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...       ...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  
3240   3952.0   1154.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3241   6238.0   1435.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3242   2432.0    545.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3243  36225.0  10278.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3244   9222.0   2838.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[3245 rows x 92 columns]

Convert to np.array.

In [20]:
sample_read_np = sample_read.to_numpy()
sample_read_np

array([[   37.105559,   -85.28138 ,  4541.      , ...,     0.      ,
            0.      ,     0.      ],
       [   36.75077 ,   -86.192458,  4549.      , ...,     0.      ,
            0.      ,     0.      ],
       [   38.005396,   -84.986417,  5407.      , ...,     0.      ,
            0.      ,     0.      ],
       ...,
       [   39.020034,   -81.382975,  1102.      , ...,     0.      ,
            0.      ,     0.      ],
       [   39.211602,   -81.516234, 18959.      , ...,     0.      ,
            0.      ,     0.      ],
       [   37.60366 ,   -81.549032,  4428.      , ...,     0.      ,
            0.      ,     0.      ]])

### Extraction of Nonzero Columns (features) and Problematic Rows (sample points)

For a column feature, we need to make sure that the column is nonzero. This is because if a column $c$ is zero, the *standardization* $$\dfrac{c - \mathrm{mean}\,(c)}{\mathrm{std}\,(c)}$$ is undefined (in this case it is `nan`).

Additionally, there still exist sample points with `nan` entries in the first and second rows (when the county location cannot be found). We will also remove those too.

In [21]:
from opioid_crisis_lib import find_nonzero, keep_rows, keep_cols
nonzero_index, zero_index = find_nonzero(sample_read_np.T)
zero_index

[23, 27, 34, 40, 41, 43, 58, 62, 65, 75, 82, 83, 84]

Identify the features these zero indices correspond to.

In [22]:
geo_features = np.array(["INTPTLAT", "INTPTLONG                                                                                                               "])
features = np.concatenate((geo_features, 
                          sorted(f_index),
                          sorted(substanceNamesDict)))

In [23]:
features[zero_index]

array(['3,4-Methylenedioxy U-47700', '4-Methylfentanyl', 'Benzylfentanyl',
       'Crotonyl fentanyl', 'Cyclopentyl fentanyl',
       'Cyclopropyl/Crotonyl Fentanyl', 'Isobutyryl fentanyl',
       'Metazocine', 'Methoxyacetyl fentanyl', 'Phenyl fentanyl',
       'U-48800', 'U-49900', 'U-51754'], dtype='<U120')

Identify the features the nonzero indices correspond to.

In [24]:
nonzero_features = features[nonzero_index]
nonzero_features

array(['INTPTLAT',
       'INTPTLONG                                                                                                               ',
       'Estimate; ANCESTRY - Total population',
       'Estimate; EDUCATIONAL ATTAINMENT - Population 25 years and over',
       'Estimate; FERTILITY - Number of women 15 to 50 years old who had a birth in the past 12 months',
       'Estimate; GRANDPARENTS - Number of grandparents living with own grandchildren under 18 years',
       'Estimate; GRANDPARENTS - Number of grandparents responsible for own grandchildren under 18 years',
       'Estimate; HOUSEHOLDS BY TYPE - Households with one or more people 65 years and over',
       'Estimate; HOUSEHOLDS BY TYPE - Households with one or more people under 18 years',
       'Estimate; HOUSEHOLDS BY TYPE - Total households',
       'Estimate; LANGUAGE SPOKEN AT HOME - Population 5 years and over',
       'Estimate; MARITAL STATUS - Females 15 years and over',
       'Estimate; MARITAL STATUS 

In [46]:
nonzero_features.shape

(79,)

These are drugs which are not included in the 2010-2016 dataframes. We will construct a matrix without these features.

In [25]:
# sample matrix with nonzero columns only.
sample_nz_col = keep_cols(sample_read_np, nonzero_index)
sample_nz_col

array([[   37.105559,   -85.28138 ,  4541.      , ...,     0.      ,
            0.      ,     0.      ],
       [   36.75077 ,   -86.192458,  4549.      , ...,     0.      ,
            0.      ,     0.      ],
       [   38.005396,   -84.986417,  5407.      , ...,     0.      ,
            0.      ,     0.      ],
       ...,
       [   39.020034,   -81.382975,  1102.      , ...,     0.      ,
            0.      ,     0.      ],
       [   39.211602,   -81.516234, 18959.      , ...,     0.      ,
            0.      ,     0.      ],
       [   37.60366 ,   -81.549032,  4428.      , ...,     0.      ,
            0.      ,     0.      ]])

Next we identify all sample points with missing location.

In [26]:
# locatable indices.
keep_row_indices = np.argwhere(~np.isnan(sample_nz_col.T[0])).T[0]
keep_row_indices

array([   0,    1,    2, ..., 3242, 3243, 3244])

In [27]:
sample_nz = sample_nz_col[keep_row_indices]
sample_nz

array([[   37.105559,   -85.28138 ,  4541.      , ...,     0.      ,
            0.      ,     0.      ],
       [   36.75077 ,   -86.192458,  4549.      , ...,     0.      ,
            0.      ,     0.      ],
       [   38.005396,   -84.986417,  5407.      , ...,     0.      ,
            0.      ,     0.      ],
       ...,
       [   39.020034,   -81.382975,  1102.      , ...,     0.      ,
            0.      ,     0.      ],
       [   39.211602,   -81.516234, 18959.      , ...,     0.      ,
            0.      ,     0.      ],
       [   37.60366 ,   -81.549032,  4428.      , ...,     0.      ,
            0.      ,     0.      ]])

Identify the sample points corresonding to the kept rows.

In [68]:
from opioid_crisis_lib import identify_sample_points
sample_point_id = identify_sample_points(keep_row_indices, ddf_yyyy)
sample_point_id

array([['2010', 'ky', 'Adair'],
       ['2010', 'ky', 'Allen'],
       ['2010', 'ky', 'Anderson'],
       ...,
       ['2016', 'wv', 'Wirt'],
       ['2016', 'wv', 'Wood'],
       ['2016', 'wv', 'Wyoming']], dtype=object)

In [69]:
sample_point_id.shape

(3007, 3)

These will be readily available.

In [72]:
sample_point_id_join = np.array([' '.join(sample_point_id[i]) for i in range(len(sample_point_id))])
sample_point_id_join

array(['2010 ky Adair', '2010 ky Allen', '2010 ky Anderson', ...,
       '2016 wv Wirt', '2016 wv Wood', '2016 wv Wyoming'], dtype='<U22')

### Standardization.

We standardize each feature column $c$: $$\tilde{c} = \dfrac{c - \mathrm{mean}\,(c)}{\mathrm{std}\,(c)}$$

In [81]:
from opioid_crisis_lib import standardize
sample_standardized = standardize(sample_nz)
sample_standardized

array([[-1.12498263, -1.16933153, -0.37244471, ..., -0.02099066,
        -0.01823919, -0.01823919],
       [-1.35792326, -1.44545842, -0.37226755, ..., -0.02099066,
        -0.01823919, -0.01823919],
       [-0.53418474, -1.07993499, -0.35326706, ..., -0.02099066,
        -0.01823919, -0.01823919],
       ...,
       [ 0.13198701,  0.01218581, -0.4486017 , ..., -0.02099066,
        -0.01823919, -0.01823919],
       [ 0.25776309, -0.02820194, -0.05315669, ..., -0.02099066,
        -0.01823919, -0.01823919],
       [-0.79794894, -0.03814226, -0.37494711, ..., -0.02099066,
        -0.01823919, -0.01823919]])

We can imbue this standardized matrix with its original features and identifiers (standardized).

In [82]:
df_standardized = pd.DataFrame(sample_standardized, index=sample_point_id_join,
                              columns=nonzero_features)
df_standardized

INTPTLAT  \
2010 ky Adair    -1.124983   
2010 ky Allen    -1.357923   
2010 ky Anderson -0.534185   
2010 ky Ballard  -1.160592   
2010 ky Barren   -1.218709   
...                    ...   
2016 wv Webster  -0.220307   
2016 wv Wetzel    0.511575   
2016 wv Wirt      0.131987   
2016 wv Wood      0.257763   
2016 wv Wyoming  -0.797949   

                  INTPTLONG                                                                                                                 \
2010 ky Adair                                             -1.169332                                                                          
2010 ky Allen                                             -1.445458                                                                          
2010 ky Anderson                                          -1.079935                                                                          
2010 ky Ballard                                           -2.299502                                                                          
2010 ky Barren                                            -1.366552                                                                          
...                                                             ...                                                                          
2016 wv Webster                                            0.295237                                                                          
2016 wv Wetzel                                             0.238759                                                                          
2016 wv Wirt                                               0.012186                                                                          
2016 wv Wood                                              -0.028202                                                                          
2016 wv Wyoming                                           -0.038142                                                                          

                  Estimate; ANCESTRY - Total population  \
2010 ky Adair                                 -0.372445   
2010 ky Allen                                 -0.372268   
2010 ky Anderson                              -0.353267   
2010 ky Ballard                               -0.430686   
2010 ky Barren                                -0.258353   
...                                                 ...   
2016 wv Webster                               -0.439965   
2016 wv Wetzel                                -0.406105   
2016 wv Wirt                                  -0.448602   
2016 wv Wood                                  -0.053157   
2016 wv Wyoming                               -0.374947   

                  Estimate; EDUCATIONAL ATTAINMENT - Population 25 years and over  \
2010 ky Adair                                             -0.353385                 
2010 ky Allen                                             -0.295814                 
2010 ky Anderson                                          -0.255220                 
2010 ky Ballard                                           -0.489929                 
2010 ky Barren                                            -0.081033                 
...                                                             ...                 
2016 wv Webster                                           -0.375527                 
2016 wv Wetzel                                            -0.393241                 
2016 wv Wirt                                              -0.515762                 
2016 wv Wood                                               0.108653                 
2016 wv Wyoming                                           -0.183626                 

                  Estimate; FERTILITY - Number of women 15 to 50 years old who had a birth in the past 12 months  \
2010 ky Adair                                             -0.394772                                       

## Principal Component Analysis

We can finally perform PCA...

In [85]:
u, s, vh = np.linalg.svd(sample_standardized.T)

Here are the singular values.

In [91]:
s

array([2.66588449e+02, 1.21846628e+02, 1.06941312e+02, 9.09359806e+01,
       8.30391637e+01, 8.06563729e+01, 7.39836757e+01, 7.12824560e+01,
       6.98242407e+01, 6.38442319e+01, 6.25981603e+01, 6.04490749e+01,
       5.95685616e+01, 5.85567056e+01, 5.67395582e+01, 5.64806275e+01,
       5.61304810e+01, 5.58500135e+01, 5.53469662e+01, 5.51780780e+01,
       5.50577787e+01, 5.49661885e+01, 5.48843985e+01, 5.48401920e+01,
       5.47519348e+01, 5.43324178e+01, 5.37283565e+01, 5.32981141e+01,
       5.31394339e+01, 5.09616958e+01, 5.05588148e+01, 4.94911355e+01,
       4.92429313e+01, 4.79465964e+01, 4.66957377e+01, 4.66196652e+01,
       4.48459687e+01, 4.33995505e+01, 4.27158713e+01, 4.19599728e+01,
       4.08133660e+01, 3.87587349e+01, 3.69427182e+01, 3.55743922e+01,
       3.49387154e+01, 3.42153970e+01, 3.05129326e+01, 2.97175938e+01,
       2.90587360e+01, 2.77943003e+01, 2.54218865e+01, 2.24147734e+01,
       2.09230941e+01, 2.04833167e+01, 1.79168129e+01, 1.50872689e+01,
      

In [87]:
vh.shape

(3007, 3007)

In [89]:
s.shape

(79,)

In [90]:
s

array([2.66588449e+02, 1.21846628e+02, 1.06941312e+02, 9.09359806e+01,
       8.30391637e+01, 8.06563729e+01, 7.39836757e+01, 7.12824560e+01,
       6.98242407e+01, 6.38442319e+01, 6.25981603e+01, 6.04490749e+01,
       5.95685616e+01, 5.85567056e+01, 5.67395582e+01, 5.64806275e+01,
       5.61304810e+01, 5.58500135e+01, 5.53469662e+01, 5.51780780e+01,
       5.50577787e+01, 5.49661885e+01, 5.48843985e+01, 5.48401920e+01,
       5.47519348e+01, 5.43324178e+01, 5.37283565e+01, 5.32981141e+01,
       5.31394339e+01, 5.09616958e+01, 5.05588148e+01, 4.94911355e+01,
       4.92429313e+01, 4.79465964e+01, 4.66957377e+01, 4.66196652e+01,
       4.48459687e+01, 4.33995505e+01, 4.27158713e+01, 4.19599728e+01,
       4.08133660e+01, 3.87587349e+01, 3.69427182e+01, 3.55743922e+01,
       3.49387154e+01, 3.42153970e+01, 3.05129326e+01, 2.97175938e+01,
       2.90587360e+01, 2.77943003e+01, 2.54218865e+01, 2.24147734e+01,
       2.09230941e+01, 2.04833167e+01, 1.79168129e+01, 1.50872689e+01,
      